"""
结构化知识库赛事数据（人工校对版）

本文件由 scripts/build_curated_structured.py 自动生成。
"""

CURATED_COMPETITIONS: list[dict[str, object]] = [
    {
        "id": 1,
        "competition_name": '第七届全国青少年人工智能创新挑战赛',
        "track": '“未来校园”智能应用专项赛',
        "category": '青少年人工智能创新赛',
        "publish_time": '2024年4月',
        "registration_time": '2024年4月15日-5月15日',
        "organizer": '中国少年儿童发展服务中心',
        "official_website": 'http://www.china61.org.cn',
        "held_time": '无',
        "eligibility": '无',
        "team_size": '无',
        "advisor": '无',
        "aliases": [],
    },
    {
        "id": 2,
        "competition_name": '第七届全国青少年人工智能创新挑战赛',
        "track": '3D编程模型创新设计专项赛',
        "category": '青少年人工智能创新赛',
        "publish_time": '2024年4月',
        "registration_time": '2024年4月15日-5月15日',
        "organizer": '中国少年儿童发展服务中心',
        "official_website": 'http://www.china61.org.cn',
        "held_time": '无',
        "eligibility": '无',
        "team_size": '无',
        "advisor": '无',
        "aliases": ['3D编程模型创新设计专项赛', '3D 编程模型创新设计专项赛'],
    },
    {
        "id": 3,
        "competition_name": '第十二届“泰迪杯”数据挖掘挑战赛',
        "track": '数据挖掘挑战赛',
        "category": '数据挖掘 / 数据分析竞赛',
        "publish_time": '2024年2月',
        "registration_time": '2024年3月8日-4月12日',
        "organizer": '广东泰迪智能科技股份有限公司',
        "official_website": 'https://www.tipdm.org:10010',
        "held_time": '无',
        "eligibility": '无',
        "team_size": '无',
        "advisor": '无',
        "aliases": ['泰迪杯', 'TIPDM'],
    },
    {
        "id": 4,
        "competition_name": '第七届全国青少年人工智能创新挑战赛',
        "track": '编程创作与信息学专项赛',
        "category": '编程 / 信息学竞赛',
        "publish_time": '2024年4月',
        "registration_time": '2024年4月15日-5月15日',
        "organizer": '中国少年儿童发展服务中心',
        "official_website": 'http://www.china61.org.cn',
        "held_time": '无',
        "eligibility": '无',
        "team_size": '无',
        "advisor": '无',
        "aliases": [],
    },
    {
        "id": 5,
        "competition_name": '第七届全国青少年人工智能创新挑战赛',
        "track": '机器人工程设计专项赛',
        "category": '机器人 / 智能车竞赛',
        "publish_time": '2024年4月',
        "registration_time": '2024年4月15日-5月15日',
        "organizer": '中国少年儿童发展服务中心',
        "official_website": 'http://www.china61.org.cn',
        "held_time": '无',
        "eligibility": '无',
        "team_size": '无',
        "advisor": '无',
        "aliases": [],
    },
    {
        "id": 6,
        "competition_name": '第七届全国青少年人工智能创新挑战赛',
        "track": '极地资源勘探专项赛',
        "category": '人工智能 / 机器人 / 创新设计',
        "publish_time": '2024年4月',
        "registration_time": '2024年4月15日-5月15日',
        "organizer": '中国少年儿童发展服务中心',
        "official_website": 'http://www.china61.org.cn',
        "held_time": '无',
        "eligibility": '无',
        "team_size": '无',
        "advisor": '无',
        "aliases": [],
    },
    {
        "id": 7,
        "competition_name": '第七届全国青少年人工智能创新挑战赛',
        "track": '竞技机器人专项赛',
        "category": '机器人 / 智能车竞赛',
        "publish_time": '2024年4月',
        "registration_time": '2024年4月15日-5月15日',
        "organizer": '中国少年儿童发展服务中心',
        "official_website": 'http://www.china61.org.cn',
        "held_time": '无',
        "eligibility": '无',
        "team_size": '无',
        "advisor": '无',
        "aliases": [],
    },
    {
        "id": 8,
        "competition_name": '第七届全国青少年人工智能创新挑战赛',
        "track": '开源鸿蒙机器人专项赛',
        "category": '机器人 / 智能车竞赛',
        "publish_time": '2024年4月',
        "registration_time": '2024年4月15日-5月15日',
        "organizer": '中国少年儿童发展服务中心',
        "official_website": 'http://www.china61.org.cn',
        "held_time": '无',
        "eligibility": '无',
        "team_size": '无',
        "advisor": '无',
        "aliases": [],
    },
    {
        "id": 9,
        "competition_name": '第七届全国青少年人工智能创新挑战赛',
        "track": '人工智能综合创新专项赛',
        "category": '人工智能 / 机器人 / 创新设计',
        "publish_time": '2024年4月',
        "registration_time": '2024年4月15日-5月15日',
        "organizer": '中国少年儿童发展服务中心',
        "official_website": 'http://www.china61.org.cn',
        "held_time": '无',
        "eligibility": '无',
        "team_size": '无',
        "advisor": '无',
        "aliases": [],
    },
    {
        "id": 10,
        "competition_name": '第七届全国青少年人工智能创新挑战赛',
        "track": '三维程序创意设计专项赛',
        "category": '人工智能 / 机器人 / 创新设计',
        "publish_time": '2024年4月',
        "registration_time": '2024年4月15日-5月15日',
        "organizer": '中国少年儿童发展服务中心',
        "official_website": 'http://www.china61.org.cn',
        "held_time": '无',
        "eligibility": '无',
        "team_size": '无',
        "advisor": '无',
        "aliases": [],
    },
    {
        "id": 11,
        "competition_name": '第七届全国青少年人工智能创新挑战赛',
        "track": '生成式人工智能应用专项赛',
        "category": '人工智能 / 机器人 / 创新设计',
        "publish_time": '2024年4月',
        "registration_time": '2024年4月15日-5月15日',
        "organizer": '中国少年儿童发展服务中心',
        "official_website": 'http://www.china61.org.cn',
        "held_time": '无',
        "eligibility": '无',
        "team_size": '无',
        "advisor": '无',
        "aliases": [],
    },
    {
        "id": 12,
        "competition_name": '第七届全国青少年人工智能创新挑战赛',
        "track": '太空电梯工程设计专项赛',
        "category": '人工智能 / 机器人 / 创新设计',
        "publish_time": '2024年4月',
        "registration_time": '2024年4月15日-5月15日',
        "organizer": '中国少年儿童发展服务中心',
        "official_website": 'http://www.china61.org.cn',
        "held_time": '无',
        "eligibility": '无',
        "team_size": '无',
        "advisor": '无',
        "aliases": [],
    },
    {
        "id": 13,
        "competition_name": '第七届全国青少年人工智能创新挑战赛',
        "track": '太空探索智能机器人专项赛',
        "category": '机器人 / 智能车竞赛',
        "publish_time": '2024年4月',
        "registration_time": '2024年4月15日-5月15日',
        "organizer": '中国少年儿童发展服务中心',
        "official_website": 'http://www.china61.org.cn',
        "held_time": '无',
        "eligibility": '无',
        "team_size": '无',
        "advisor": '无',
        "aliases": [],
    },
    {
        "id": 14,
        "competition_name": '第七届全国青少年人工智能创新挑战赛',
        "track": '无人驾驶智能车专项赛',
        "category": '机器人 / 智能车竞赛',
        "publish_time": '2024年4月',
        "registration_time": '2024年4月15日-5月15日',
        "organizer": '中国少年儿童发展服务中心',
        "official_website": 'http://www.china61.org.cn',
        "held_time": '无',
        "eligibility": '无',
        "team_size": '无',
        "advisor": '无',
        "aliases": [],
    },
    {
        "id": 15,
        "competition_name": '第七届全国青少年人工智能创新挑战赛',
        "track": '虚拟仿真平台创新设计专项赛',
        "category": '人工智能 / 机器人 / 创新设计',
        "publish_time": '2024年4月',
        "registration_time": '2024年4月15日-5月15日',
        "organizer": '中国少年儿童发展服务中心',
        "official_website": 'http://www.china61.org.cn',
        "held_time": '无',
        "eligibility": '无',
        "team_size": '无',
        "advisor": '无',
        "aliases": [],
    },
    {
        "id": 16,
        "competition_name": '第七届全国青少年人工智能创新挑战赛',
        "track": '智慧城市主题设计专项赛',
        "category": '人工智能 / 机器人 / 创新设计',
        "publish_time": '2024年4月',
        "registration_time": '2024年4月15日-5月15日',
        "organizer": '中国少年儿童发展服务中心',
        "official_website": 'http://www.china61.org.cn',
        "held_time": '无',
        "eligibility": '无',
        "team_size": '无',
        "advisor": '无',
        "aliases": [],
    },
    {
        "id": 17,
        "competition_name": '第七届全国青少年人工智能创新挑战赛',
        "track": '智能数据采集装置设计专项赛',
        "category": '人工智能 / 机器人 / 创新设计',
        "publish_time": '2024年4月',
        "registration_time": '2024年4月15日-5月15日',
        "organizer": '中国少年儿童发展服务中心',
        "official_website": 'http://www.china61.org.cn',
        "held_time": '无',
        "eligibility": '无',
        "team_size": '无',
        "advisor": '无',
        "aliases": [],
    },
    {
        "id": 18,
        "competition_name": '第七届全国青少年人工智能创新挑战赛',
        "track": '智能芯片与计算思维专项赛',
        "category": '人工智能 / 机器人 / 创新设计',
        "publish_time": '2024年4月',
        "registration_time": '2024年4月15日-5月15日',
        "organizer": '中国少年儿童发展服务中心',
        "official_website": 'http://www.china61.org.cn',
        "held_time": '无',
        "eligibility": '无',
        "team_size": '无',
        "advisor": '无',
        "aliases": [],
    },
    {
        "id": 19,
        "competition_name": '“高教社杯”全国大学生数学建模竞赛',
        "track": '/',
        "category": '数学建模竞赛',
        "publish_time": '无',
        "registration_time": '无',
        "organizer": '中国工业与应用数学学会',
        "official_website": 'http://www.mcm.edu.cn',
        "held_time": '每年9月',
        "eligibility": '本科和高职高专学生均可参赛',
        "team_size": '每队3人',
        "advisor": '无',
        "aliases": ['CUMCM', '全国大学生数学建模竞赛', '高教社杯'],
    },
    {
        "id": 20,
        "competition_name": '“华为杯”中国研究生数学建模竞赛',
        "track": '/',
        "category": '数学建模竞赛',
        "publish_time": '无',
        "registration_time": '无',
        "organizer": '中国研究生数学建模竞赛组织委员会',
        "official_website": 'http://www.shumo.com',
        "held_time": '每年9月',
        "eligibility": '仅限研究生参赛',
        "team_size": '每队3-6人',
        "advisor": '无',
        "aliases": ['研究生数学建模竞赛', '华为杯研究生数模', '华为杯'],
    },
    {
        "id": 21,
        "competition_name": '“深圳杯”数学建模挑战赛',
        "track": '/',
        "category": '数学建模竞赛',
        "publish_time": '无',
        "registration_time": '无',
        "organizer": '深圳市科学技术协会',
        "official_website": 'http://szb2024.m2ct.org/team/login',
        "held_time": '无',
        "eligibility": '本硕博及爱好者均可组队参加',
        "team_size": '每队不超过4人',
        "advisor": '不设指导教师',
        "aliases": ['深圳杯数学建模挑战赛', '深圳杯'],
    },
    {
        "id": 22,
        "competition_name": '第十六届全国大学生电子商务“创新、创意及创业”挑战赛',
        "track": '“创新创意及创业”挑战赛常规赛',
        "category": '创新创业类竞赛',
        "publish_time": '2025年10月20日',
        "registration_time": '2025年10月20日-2025年12月31日',
        "organizer": '全国电子商务产教融合创新联盟、西安交通大学',
        "official_website": 'http://www.3chuang.net',
        "held_time": '2026年3月-2026年8月',
        "eligibility": '全日制在校大学生（专科/本科/研究生）',
        "team_size": '3-5人',
        "advisor": '0-2名高校教师+0-2名企业教师',
        "aliases": ['三创赛', '电子商务三创赛'],
    },
    {
        "id": 23,
        "competition_name": '电子信息类',
        "track": '2025年全国大学生电子设计竞赛（本科生组、高职高专组）',
        "category": '全国性大学生学科竞赛',
        "publish_time": '2025年01月17日',
        "registration_time": '2025年5月31日截止',
        "organizer": '全国竞赛组委会、各赛区竞赛组委会',
        "official_website": '全国大学生电子设计竞赛网站（http://nuedc.xjtu.edu.cn）、全国大学生电子设计竞赛培训网（https://nuedc-training.com.cn）',
        "held_time": '2025年7月30日 8:00 至 8月2日 20:00',
        "eligibility": '普通高等学校具有正式学籍的全日制在校本科或高职高专学生',
        "team_size": '3人',
        "advisor": '无',
        "aliases": ['全国大学生电子设计竞赛'],
    },
]
